### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by thecodeduchess** [timfox68/teaCozy#2]
https://github.com/timfox68/teaCozy/blob/ac65c3674b0b121260893d3808941a998e93da6f/index.html#L14

Images properly linked and viewable. In the future, you will be including resources within the project. The benefit of that is it ensures images will always be available for viewers. An external link hosting the images could be down due to maintenance or closing down sever.

**Comment by timfox68** [comment]
Okay thanks. Will add a resources folder in the future. Wasn't sure if that was required but makes sense to not have to rely on another site.
